### PR TITLE
feat (DEVEXP-108): Repository & artifact deprecation

### PR DESCRIPTION
**Pull request by JPPortier**

### CODE REVIEW

**Comment by Dovchik** [comment]
Can you give a context in description? I see you just remove all the stuff, but what's the idea?

**Comment by JPPortier** [comment]
> Can you give a context in description? I see you just remove all the stuff, but what's the idea?

Right: 
- updated README for deprecation
- all sources removed to be able to push an empty 0.4.0 .jar artifact onto maven repository

**Comment by Dovchik** [comment]
> > Can you give a context in description? I see you just remove all the stuff, but what's the idea?
> 
> Right:
> 
> * updated README for deprecation
> * all sources removed to be able to push an empty 0.4.0 .jar artifact onto maven repository

So, if I'm correct - this repo will become a host for the new java sdk?

**Comment by JPPortier** [comment]
> > > Can you give a context in description? I see you just remove all the stuff, but what's the idea?
> > 
> > 
> > Right:
> > 
> > * updated README for deprecation
> > * all sources removed to be able to push an empty 0.4.0 .jar artifact onto maven repository
> 
> So, if I'm correct - this repo will become a host for the new java sdk?
This will one will be archived like others deprecated repos.
The new java SDK repository will be 'sinch-sdk-java'  to keep same naming pattern for all SDKs (this imply the already deprecated previous sinch-sdk-java will have to be renamed or "moved")

**Comment by Dovchik** [comment]
So why remove stuff - if there is [archive](https://docs.github.com/en/repositories/archiving-a-github-repository/archiving-repositories) - and pushing empty artifact?

**Comment by JPPortier** [comment]
> So why remove stuff - if there is [archive](https://docs.github.com/en/repositories/archiving-a-github-repository/archiving-repositories) - and pushing empty artifact?

new (empty) artifact will reflect repository content

**Review by Dovchik — APPROVED** [review]

**Pull request merged**
